In [21]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import seaborn as sn
sn.set(style='whitegrid')

Load training Data

In [22]:
x_train = pd.read_csv('housing_train_clean.csv')
y_train = x_train['SalePrice']
x_train.drop('SalePrice', axis = 1)

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,BsmtCond_Fa,...,Street_Grvl,Street_Pave,TotRmsAbvGrd,TotalBsmtSF,Utilities_AllPub,Utilities_NoSeWa,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,3,1,0,0,0,0,0,...,0,1,8,856,1,0,0,2003,2003,2008
1,1262,0,0,3,1,0,0,0,0,0,...,0,1,6,1262,1,0,298,1976,1976,2007
2,920,866,0,3,1,0,0,0,0,0,...,0,1,6,920,1,0,0,2001,2002,2008
3,961,756,0,3,1,0,0,0,0,0,...,0,1,7,756,1,0,0,1915,1970,2006
4,1145,1053,0,4,1,0,0,0,0,0,...,0,1,9,1145,1,0,192,2000,2000,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,953,694,0,3,1,0,0,0,0,0,...,0,1,7,953,1,0,0,1999,2000,2007
1456,2073,0,0,3,1,0,0,0,0,0,...,0,1,7,1542,1,0,349,1978,1988,2010
1457,1188,1152,0,4,1,0,0,0,0,0,...,0,1,9,1152,1,0,0,1941,2006,2010
1458,1078,0,0,2,1,0,0,0,0,0,...,0,1,5,1078,1,0,366,1950,1996,2010
1459,1256,0,0,3,1,0,0,0,0,0,...,0,1,6,1256,1,0,736,1965,1965,2008

In [23]:
y_train

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

Load Test Data

In [24]:
x_test = pd.read_csv('housing_test_clean.csv')
y_test = x_test['SalePrice']
x_test.drop('SalePrice', axis = 1)

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,BsmtCond_Fa,...,Street_Grvl,Street_Pave,TotRmsAbvGrd,TotalBsmtSF,Utilities_AllPub,Utilities_NoSeWa,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,896,0,0,2,1,0,0,0,0,0,...,0,1,5,882.0,1,0,140,1961,1961,2010
1,1329,0,0,3,1,0,0,0,0,0,...,0,1,6,1329.0,1,0,393,1958,1958,2010
2,928,701,0,3,1,0,0,0,0,0,...,0,1,6,928.0,1,0,212,1997,1998,2010
3,926,678,0,3,1,0,0,0,0,0,...,0,1,7,926.0,1,0,360,1998,1998,2010
4,1280,0,0,2,0,0,0,0,1,0,...,0,1,5,1280.0,1,0,0,1992,1992,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,546,546,0,3,0,0,0,1,0,0,...,0,1,5,546.0,1,0,0,1970,1970,2006
1455,546,546,0,3,0,0,0,0,1,0,...,0,1,6,546.0,1,0,0,1970,1970,2006
1456,1224,0,0,4,1,0,0,0,0,0,...,0,1,7,1224.0,1,0,474,1960,1996,2006
1457,970,0,0,3,1,0,0,0,0,0,...,0,1,6,912.0,1,0,80,1992,1992,2006
1458,996,1004,0,3,1,0,0,0,0,0,...,0,1,9,996.0,1,0,190,1993,1994,2006

In [25]:
y_test

0       120376.994315
1       152387.635505
2       185025.193763
3       198385.651258
4       185934.885245
            ...
1454     85890.984520
1455     83811.680275
1456    160189.586559
1457    115398.604894
1458    224009.963740
Name: SalePrice, Length: 1459, dtype: float64

Convert Pandas to Numpy Array

In [26]:
x_train = x_train.values
y_train = y_train.values.reshape(-1)
x_test = x_test.values
y_test = y_test.values.reshape(-1)

Normalize x_train and x_test using minmaxscaler

In [27]:
scaler=MinMaxScaler()
#get the parameters of the transform
scaler.fit(x_train)
#normalize the features in the training set
x_train_s = scaler.transform(x_train)
#normalize the features in the test set
x_test_s = scaler.transform(x_test)

from sklearn.model_selection import train_test_split

x_train_s, x_val_s, y_train, y_val = train_test_split(x_train_s, y_train, test_size=0.1, random_state=0)

KNeighborsRegressor (n_neighbors)

parameter range: 1 to 100, with the step of 10

In [28]:
from sklearn.neighbors import KNeighborsRegressor
MAPEsKNN = {}
for x in range(1, 101, 10):
    knn = KNeighborsRegressor(n_neighbors = x)
    # train the KNN regressor
    knn.fit(x_train_s, y_train)
    # test the KNN regressor
    Y_val_pred_knn = knn.predict(x_val_s)
    # Calculate errors on test set
    #MSE = np.mean((y_test - Y_test_pred_knn)**2)
    #MAE = np.mean(np.abs(y_test - Y_test_pred_knn))
    MAPE =  np.mean(np.abs(y_val - Y_val_pred_knn)/y_val)
    print(x, ':     ', MAPE)
    MAPEsKNN[x] = MAPE
print()
print('Optimal n_neighbors : MAPE')
print(min(MAPEsKNN, key = MAPEsKNN.get), end=': ')
print(min(MAPEsKNN.values()))

1 :      0.15651114373831643
11 :      0.12713726831542602
21 :      0.1320935122517129
31 :      0.1386121722866331
41 :      0.1428729041111862
51 :      0.14751734159883512
61 :      0.14679772310422226
71 :      0.14922175707905802
81 :      0.15128926993704428
91 :      0.1553268223320134

Optimal n_neighbors : MAPE
11: 0.12713726831542602

In [29]:
knn = KNeighborsRegressor(n_neighbors = 11)
# train the KNN regressor
knn.fit(x_train_s, y_train)
# test the KNN regressor
Y_test_pred_knn = knn.predict(x_test_s)
# Calculate errors on test set
MSE1 = np.mean((y_test - Y_test_pred_knn)**2)
MAE1 = np.mean(np.abs(y_test - Y_test_pred_knn))
MAPE1 =  np.mean(np.abs(y_test - Y_test_pred_knn)/y_test)

DecisionTreeRegressor

In [30]:
from sklearn.tree import DecisionTreeRegressor
MAPEsDT = {}
for y in range(1, 101, 10):
    model = DecisionTreeRegressor(max_depth = y)
    model.fit(x_train_s, y_train)
    # test the regressor
    Y_val_pred_dt = model.predict(x_val_s)
    # Calculate errors
    #MSE3 = np.mean((y_test - Y_test_pred_dt)**2)
    #MAE3 = np.mean(np.abs(y_test - Y_test_pred_dt))
    MAPE =  np.mean(np.abs(y_val - Y_val_pred_dt)/y_val)
    print(y, ':     ', MAPE)
    MAPEsDT[y] = MAPE
print()
print('Optimal max_depth : MAPE')
print(min(MAPEsDT, key = MAPEsDT.get), end=': ')
print(min(MAPEsDT.values()))

1 :      0.20633696398219759
11 :      0.0014625506018243512
21 :      0.0024432724065101244
31 :      0.0027327841695380037
41 :      0.0027070711017953978
51 :      0.0015027455352209277
61 :      0.0027512045656106765
71 :      0.002574638635656805
81 :      0.0028427914118427117
91 :      0.002671169703085124

Optimal max_depth : MAPE
11: 0.0014625506018243512

In [35]:
model = DecisionTreeRegressor(max_depth = 11)
model.fit(x_train_s, y_train)
# test the regressor
Y_test_pred_dt = model.predict(x_test_s)
# Calculate errors
MSE2 = np.mean((y_test - Y_test_pred_dt)**2)
MAE2 = np.mean(np.abs(y_test - Y_test_pred_dt))
MAPE2 =  np.mean(np.abs(y_test - Y_test_pred_dt)/y_test)

RandomForestRegressor

In [36]:
from sklearn.ensemble import RandomForestRegressor
MAPEsRF = {}
for z in range(1, 101, 10):
    RF = RandomForestRegressor(max_depth = z)
    RF.fit(x_train_s, y_train)
    Y_val_pred_rf = RF.predict(x_val_s)
    MAPE =  np.mean(np.abs(y_val - Y_val_pred_rf)/y_val)
    print(z, ':     ', MAPE)
    MAPEsRF[z] = MAPE
print()
print('Optimal max_depth : MAPE')
print(min(MAPEsRF, key = MAPEsRF.get), end=': ')
print(min(MAPEsRF.values()))

1 :      0.19958515906858973
11 :      0.0020253532622622073
21 :      0.00211112407898676
31 :      0.002084263368333783
41 :      0.0020407971335752993
51 :      0.0019630766282740094
61 :      0.0021263776587890576
71 :      0.0020237915316269573
81 :      0.002127067369053457
91 :      0.0020403580324384113

Optimal max_depth : MAPE
51: 0.0019630766282740094

In [39]:
model = DecisionTreeRegressor(max_depth = 51)
model.fit(x_train_s, y_train)
# test the regressor
Y_test_pred_dt = model.predict(x_test_s)
# Calculate errors
MSE3 = np.mean((y_test - Y_test_pred_dt)**2)
MAE3 = np.mean(np.abs(y_test - Y_test_pred_dt))
MAPE3 =  np.mean(np.abs(y_test - Y_test_pred_dt)/y_test)

Construct Dataframe

In [40]:
dict = {
        'KNN':[MSE1, MAE1, MAPE1],
        'Decision Tree':[MSE2, MAE2, MAPE2],
        'Random Forest':[MSE3, MAE3, MAPE3]}

results = pd.DataFrame(dict, index = ['MSE' ,'MAE', 'MAPE' ])
results

               KNN  Decision Tree  Random Forest
MSE   1.413399e+09   1.815277e+08   2.221333e+08
MAE   2.299028e+04   1.161560e+03   1.231791e+03
MAPE  1.283712e-01   3.875830e-03   3.858057e-03