In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import seaborn as sn
sn.set(style='whitegrid')

In [2]:
X_train = pd.read_csv("housing_train_clean.csv")

X_train =  X_train.drop('SalePrice', axis=1)
X_train.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,BsmtCond_Fa,...,Street_Grvl,Street_Pave,TotRmsAbvGrd,TotalBsmtSF,Utilities_AllPub,Utilities_NoSeWa,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,3,1,0,0,0,0,0,...,0,1,8,856,1,0,0,2003,2003,2008
1,1262,0,0,3,1,0,0,0,0,0,...,0,1,6,1262,1,0,298,1976,1976,2007
2,920,866,0,3,1,0,0,0,0,0,...,0,1,6,920,1,0,0,2001,2002,2008
3,961,756,0,3,1,0,0,0,0,0,...,0,1,7,756,1,0,0,1915,1970,2006
4,1145,1053,0,4,1,0,0,0,0,0,...,0,1,9,1145,1,0,192,2000,2000,2008

In [3]:
data_train = pd.read_csv("housing_train.csv")

Y_train = data_train['SalePrice']
Y_train.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [4]:
X_test = pd.read_csv("housing_test_clean.csv")
X_test = X_test.drop('SalePrice', axis=1)
X_test

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,BsmtCond_Fa,...,Street_Grvl,Street_Pave,TotRmsAbvGrd,TotalBsmtSF,Utilities_AllPub,Utilities_NoSeWa,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,896,0,0,2,1,0,0,0,0,0,...,0,1,5,882.0,1,0,140,1961,1961,2010
1,1329,0,0,3,1,0,0,0,0,0,...,0,1,6,1329.0,1,0,393,1958,1958,2010
2,928,701,0,3,1,0,0,0,0,0,...,0,1,6,928.0,1,0,212,1997,1998,2010
3,926,678,0,3,1,0,0,0,0,0,...,0,1,7,926.0,1,0,360,1998,1998,2010
4,1280,0,0,2,0,0,0,0,1,0,...,0,1,5,1280.0,1,0,0,1992,1992,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,546,546,0,3,0,0,0,1,0,0,...,0,1,5,546.0,1,0,0,1970,1970,2006
1455,546,546,0,3,0,0,0,0,1,0,...,0,1,6,546.0,1,0,0,1970,1970,2006
1456,1224,0,0,4,1,0,0,0,0,0,...,0,1,7,1224.0,1,0,474,1960,1996,2006
1457,970,0,0,3,1,0,0,0,0,0,...,0,1,6,912.0,1,0,80,1992,1992,2006
1458,996,1004,0,3,1,0,0,0,0,0,...,0,1,9,996.0,1,0,190,1993,1994,2006

In [5]:
Y_test = pd.read_csv('housing_test_y.csv')
Y_test = Y_test['SalePrice']
Y_test

0       120376.994315
1       152387.635505
2       185025.193763
3       198385.651258
4       185934.885245
            ...
1454     85890.984520
1455     83811.680275
1456    160189.586559
1457    115398.604894
1458    224009.963740
Name: SalePrice, Length: 1459, dtype: float64

In [6]:
X_train=X_train.values
Y_train=Y_train.values.reshape(-1)
X_test=X_test.values
Y_test=Y_test.values.reshape(-1)

In [7]:
print(X_test.shape, Y_test.shape)

(1459, 275) (1459,)

In [8]:
#Normalize features

scaler=MinMaxScaler()
#get the parameters of the transform
scaler.fit(X_train)
#normalize the features in the training set
X_train_s = scaler.transform(X_train)
#normalize the features in the test set
X_test_s = scaler.transform(X_test)

from sklearn.model_selection import train_test_split

X_train_s, X_val_s, Y_train, Y_val = train_test_split(X_train_s, Y_train, test_size=0.1, random_state=0)

In [9]:
# KNeighborsRegressor (n_neighbors)
# DecisionTreeRegressor (max_depth)
# RandomForestRegressor (max_depth)
# (see examples presented in class)
# parameter range: 1 to 100, with the step of 10

In [10]:
# K nieghbors regression 
from sklearn.neighbors import KNeighborsRegressor
MSE_K_list = []
MAE_K_list = []
MAPE_K_list = []
for x in range(1, 101, 10):
    knn = KNeighborsRegressor(n_neighbors = x)
    # train the KNN regressor
    knn.fit(X_train_s, Y_train)
    # test the KNN regressor
    Y_val_pred = knn.predict(X_val_s)
    # Calculate errors on validation set
    MSE_K = np.mean((Y_val - Y_val_pred)**2)
    MAE_K = np.mean(np.abs(Y_val - Y_val_pred))
    MAPE_K =  np.mean(np.abs(Y_val - Y_val_pred)/Y_val)
    MSE_K_list.append(MSE_K)
    MAE_K_list.append(MAE_K)
    MAPE_K_list.append(MAPE_K)
#     print('MSE=', MSE_K)
#     print('MAE=', MAE_K)
    print('MAPE=', MAPE_K, 'for', x)

# min_MSE_K = min(MSE_K_list)
# min_MAE_K = min(MAE_K_list)
# min_MAPE_K = min(MAPE_K_list)

# print("min mse:", min_MSE_K)
# print("min mae:", min_MAE_K)
# print("min mape:", min_MAPE_K)

MAPE= 0.15651114373831643 for 1
MAPE= 0.12905488986463806 for 11
MAPE= 0.13229179074486982 for 21
MAPE= 0.1390955322612947 for 31
MAPE= 0.14362822980564474 for 41
MAPE= 0.1475341550724143 for 51
MAPE= 0.14738715785578563 for 61
MAPE= 0.14951278740387966 for 71
MAPE= 0.15195816821254632 for 81
MAPE= 0.15564137953217383 for 91

In [11]:
# testing the K neighbors Regressor on the test set

knn = KNeighborsRegressor(n_neighbors = 11)
# train the KNN regressor
knn.fit(X_train_s, Y_train)
# test the KNN regressor
Y_test_pred = knn.predict(X_test_s)
# Calculate errors on validation set
MSE_K = np.mean((Y_test - Y_test_pred)**2)
MAE_K = np.mean(np.abs(Y_test - Y_test_pred))
MAPE_K =  np.mean(np.abs(Y_test - Y_test_pred)/Y_test)
# MSE_K_list.append(MSE_K)
# MAE_K_list.append(MAE_K)
# MAPE_K_list.append(MAPE_K)
print('MSE=', MSE_K)
print('MAE=', MAE_K)
print('MAPE=', MAPE_K)

MSE= 1367156611.8916905
MAE= 22400.35006252411
MAPE= 0.12517100604280934

In [12]:
# DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

In [13]:

MSE_T_list = []
MAE_T_list= []
MAPE_T_list = []

for y in range(1, 101, 10):
    model = DecisionTreeRegressor(max_depth=y)
    model.fit(X_train_s, Y_train)

    # test the regressor
    Y_val_pred = model.predict(X_val_s)
    # Calculate errors
    MSE_T = np.mean((Y_val - Y_val_pred)**2)
    MAE_T = np.mean(np.abs(Y_val - Y_val_pred))
    MAPE_T =  np.mean(np.abs(Y_val - Y_val_pred)/Y_val)
#     print('MSE=', MSE_T)
#     print('MAE=', MAE_T)
    print('MAPE=', MAPE_T, 'for', y)
    MSE_T_list.append(MSE_T)
    MAE_T_list.append(MAE_T)
    MAPE_T_list.append(MAPE_T)

# min_MSE_T = min(MSE_T_list)
# min_MAE_T =  min(MAE_T_list)
# min_MAPE_T = min(MAPE_T_list)

# print("min mse:", min_MSE_T)
# print("min mae:", min_MAE_T)
# print("min mape:", min_MAPE_T)

MAPE= 0.24061030749919673 for 1
MAPE= 0.13009000315603508 for 11
MAPE= 0.13909561667819595 for 21
MAPE= 0.14282191726994994 for 31
MAPE= 0.1305421785901169 for 41
MAPE= 0.1443199662643882 for 51
MAPE= 0.14166820242975772 for 61
MAPE= 0.13970876030132168 for 71
MAPE= 0.1335176143040162 for 81
MAPE= 0.13937406544395484 for 91

In [14]:
# best MAPE= 0.132044151366305 for 11
model = DecisionTreeRegressor(max_depth=11)
model.fit(X_train_s, Y_train)

# test the regressor
Y_test_pred = model.predict(X_test_s)
# Calculate errors
MSE_T = np.mean((Y_test - Y_test_pred)**2)
MAE_T = np.mean(np.abs(Y_test - Y_test_pred))
MAPE_T =  np.mean(np.abs(Y_test - Y_test_pred)/Y_test)
#     print('MSE=', MSE_T)
#     print('MAE=', MAE_T)
print('MAPE=', MAPE_T)
MSE_T_list.append(MSE_T)
MAE_T_list.append(MAE_T)
MAPE_T_list.append(MAPE_T)

MAPE= 0.12183157066062145

In [15]:
# Random Forest Regressor
# Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

In [16]:


MSE_RF_list = []
MAE_RF_list= []
MAPE_RF_list = []


for z in range(1, 100, 10):
    RF = RandomForestRegressor(max_depth=z)
    RF.fit(X_train_s, Y_train)
    #RF.score(X_test, Y_test)
    Y_val_pred = RF.predict(X_val_s)
    # Calculate errors
    MSE_RF = np.mean((Y_val - Y_val_pred)**2)
    MAE_RF = np.mean(np.abs(Y_val - Y_val_pred))
    MAPE_RF =  np.mean(np.abs(Y_val - Y_val_pred)/Y_val)
#     print('MSE=', MSE_RF)
#     print('MAE=', MAE_RF)
    print('MAPE=', MAPE_RF, 'for', z)
    MSE_RF_list.append(MSE_RF)
    MAE_RF_list.append(MAE_RF)
    MAPE_RF_list.append(MAPE_RF)
    
# min_MSE_RF = min(MSE_RF_list)
# min_MAE_RF =  min(MAE_RF_list)
# min_MAPE_RF = min(MAPE_RF_list)
# print("min mse:", min_MSE_T)
# print("min mae:", min_MAE_T)
# print("min mape:", min_MAPE_T)

MAPE= 0.2043136056073368 for 1
MAPE= 0.08067149584668758 for 11
MAPE= 0.0801760766231927 for 21
MAPE= 0.08289483951317099 for 31
MAPE= 0.0807891935154307 for 41
MAPE= 0.0791381285190135 for 51
MAPE= 0.08216662637946412 for 61
MAPE= 0.08164378327538631 for 71
MAPE= 0.0815583809658105 for 81
MAPE= 0.08022373862505865 for 91

In [17]:
# Best max_depth - 51
# test it on the test data
RF = RandomForestRegressor(max_depth=51)
RF.fit(X_train_s, Y_train)
#RF.score(X_test, Y_test)
Y_test_pred = RF.predict(X_test_s)
# Calculate errors
MSE_RF = np.mean((Y_test - Y_test_pred)**2)
MAE_RF = np.mean(np.abs(Y_test - Y_test_pred))
MAPE_RF =  np.mean(np.abs(Y_test - Y_test_pred)/Y_test)
#     print('MSE=', MSE_RF)
#     print('MAE=', MAE_RF)
print('MAPE=', MAPE_RF)

MAPE= 0.06040320337565829

In [18]:
# make the data frame

# initialize data of lists.
data = {'KNeighborsRegressor': [MSE_K, MAE_K, MAPE_K],
        'DecisionTreeRegressor': [MSE_T, MAE_T, MAPE_T],
        'RandomForestRegressor': [MSE_RF, MAE_RF, MAPE_RF]}
  
    

# Creates pandas DataFrame.
df = pd.DataFrame(data, index=['MSE',
                               'MAE',
                               'MAPE'])

# print the data frame
df

      KNeighborsRegressor  DecisionTreeRegressor  RandomForestRegressor
MSE          1.367157e+09           1.770429e+09           5.742580e+08
MAE          2.240035e+04           2.208739e+04           1.066041e+04
MAPE         1.251710e-01           1.218316e-01           6.040320e-02